# Generated by Django 6.0.3 on 2026-03-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flutterwave_tx_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
